### ISSUE TITLE
Criar o diagrama ER

### ISSUE THREAD

**Issue by arthurmelo777** [DesempregadosTech/TaskHub#1]

**Comment by arthurmelo777** [comment]
Adicionar o png do diagrama ER na pasta docs.

**Comment by Gabriel-Cortezz** [comment]
to colocando os diagramas em pastas dentro do docs, eu creio q assim fica mais organizado...

**Comment by Gabriel-Cortezz** [comment]
Coloquei o diagrama ER, mas tenho que dá mais uma examinada, porque tem certas coisas que passam despercebidas como as entidades fracas

**Comment by Gabriel-Cortezz** [comment]
Finalizado.
